Rscript src/Ag_ScRNA_09_pseudobulk_per_celltype_limma_NTC_guide.R
Rscript src/Ag_ScRNA_10_Pseudobulk_ex_in_NTC_Enrichment_guide.R
Rscript src/Ag_ScRNA_11_Pseudobulk_limma_all_ko_ex.vivo_vs_in.vivo_per_celltype01_guide.R
#Rscript src/Ag_ScRNA_12_Pseudobulk_enrichr_per_celltype_guide.R
Rscript src/Ag_ScRNA_12_Pseudobulk_FGSEA_per_celltype_guide.R
